### ISSUE TITLE
we need a delete method to delete the nodes....  this means cascade delete not just deleting the node...

### ISSUE THREAD

**Issue by jmoseman01** [jmoseman01/youtubeindex#14]

**Comment by jmoseman01** [comment]
Cascade delete doestn't work - deleting a heading with lower level sub headings

**Comment by fractalwizz** [comment]
I was going to ask about that - I can probably use a recursive function that deletes the given node and all children

**Comment by jmoseman01** [comment]
What do you mean if it doesn't work?  We should be able to implement it.

**Comment by jmoseman01** [comment]
When I say cascade delete I don't mean in the ORM.  There is no ORM mapping in which relates the children.  I meant programmtically do a cascading delete on the children.

**Comment by fractalwizz** [comment]
Ah OK - makes sense - a recursive solution might work

**Comment by fractalwizz** [comment]
With Cascade delete now implemented, we can close this...
