### ISSUE TITLE
NuGet package - does a nuget package exist for jstree?

### ISSUE THREAD

**Issue by jmoseman01** [jmoseman01/youtubeindex#19]

**Comment by fractalwizz** [comment]
Yes, there are NuGet packages for jstree - But we already have the jstree script files and the other packages wouldn't help us...

**Comment by jmoseman01** [comment]
I actually traded out our jstree script to the NuGet package, while debugging the azure stuff.  I'd prefer the NuGet package over just the jstree script directly.  I'll push that change shortly.

**Comment by pdrow** [comment]
does that close this?

**Comment by jmoseman01** [comment]
I was going to wait to close it.  Once I push my changes up with the nuGet Package I'll close this issue.
