### ISSUE TITLE
Continue with ASP.NET or switch back to java?

### ISSUE THREAD

**Issue by jmoseman01** [jmoseman01/youtubeindex#37]
Noticing tools that I want are easier to implement on a linux server I've debated whether or not we even want to continue using the ASP.NET stack.  For instance I believe kiwi irc would be easier to implement on a linux server.  What is your guys opinion.  I'm thinking with limited time we should just stick with asp.net as we can almost implement all our buisness features for Jim easily.

**Comment by fractalwizz** [comment]
Stick with ASP.NET - mostly due to the time constraint

**Comment by jmoseman01** [comment]
For the class I'm thinking we should just stick with ASP.NET
