### ISSUE TITLE
Social Sharing of Video page

### ISSUE THREAD

**Issue by fractalwizz** [jmoseman01/youtubeindex#40]
Not mandatory for M2, but  it'd be nice to have in. I looked at a jquery plugin that'd allow for multiple social buttons to be displayed on the page easily. Initial showings are promising, but not without issues.

Sharrre is the plugin name at http:/www.Sharrre.com

First, the actual sharing buttons aren't liking the localhost URL, which might be the result of lack of page metadata. Another issue is that for the Facebook button, a like is possible, but I haven't yet found a method for FB sharing.

Additional research into this be lovely.

**Comment by JohnVCS** [comment]
I will take a look at this.

**Comment by JohnVCS** [comment]
I added the facebook share link. So far there is no associated video when we share it, but it goes to the video that we actually share.

**Comment by jmoseman01** [comment]
facebook is good for now.
