### ISSUE TITLE
PagedList.css - Jesse Deleted....

### ISSUE THREAD

**Issue by jmoseman01** [jmoseman01/youtubeindex#45]
I think I might have deleted the PagedList.css requirement.  I'm presuming this was for the paging on the node search page.  If you could push that file up.  I don't think I had it..

**Comment by fractalwizz** [comment]
Looks like it wasn't included with the project itself, despite being added by the nuGet package... - Fixing...

**Comment by jmoseman01** [comment]
I deleted it so I could push the new build.  I don't know if this css file was required or not.
