### ISSUE TITLE
'-' delimited info check

### ISSUE THREAD

**Issue by fractalwizz** [jmoseman01/youtubeindex#49]
Currently, the timestamp fetches for the last element in an array delimited by a dash '-'. However, there are certain nodes (roots) that may have text as the last element.

Need regular expression check of the last element.
If last element doesn't fit the pattern, set to default "00:00:00"

**Comment by jmoseman01** [comment]
You could strip out the colons and see if it passes as a valid number.

http://www.w3schools.com/jsref/jsref_isnan.asp

You can use !isNaN(laststr.replace(/:/g,''))

**Comment by fractalwizz** [comment]
Commit 5e2ec5f0f5826ed0b9e4575cb4de4524a9da80b9 includes the fix. Closing...
